# Generated by Django 5.1.6 on 2025-03-12 19:36

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NZ')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='placeholder.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, default='placeholder.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_Donuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('flavorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.flavour')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.order')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.type')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.customer')),
            ],
        ),
    ]
